-- ============================================================
-- Peak Performance Tutoring
-- Restore gap patch for a brand-new Supabase project
--
-- These objects are referenced by the app but were either created
-- manually in a prior project or repaired later without a base
-- CREATE TABLE migration.
-- ============================================================

-- Finance settings used by /finance/settings
CREATE TABLE IF NOT EXISTS finance_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_name TEXT NOT NULL DEFAULT 'Peak Performance Tutoring',
  org_address TEXT,
  org_phone TEXT,
  org_email TEXT,
  default_currency TEXT NOT NULL DEFAULT 'KES',
  fiscal_year_start_month INTEGER NOT NULL DEFAULT 1 CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
  pdf_footer_text TEXT DEFAULT 'Generated by Peak Performance Tutoring Finance Portal',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO finance_settings (org_name)
SELECT 'Peak Performance Tutoring'
WHERE NOT EXISTS (SELECT 1 FROM finance_settings);

ALTER TABLE finance_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "finance_settings_manage" ON finance_settings;
CREATE POLICY "finance_settings_manage" ON finance_settings
  FOR ALL
  USING (EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'finance')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'finance')
  ));

-- Teacher registration keys used by /auth/register and /admin/settings
CREATE TABLE IF NOT EXISTS teacher_registration_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_teacher_registration_keys_key
  ON teacher_registration_keys(key);

ALTER TABLE teacher_registration_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can validate teacher registration keys" ON teacher_registration_keys;
CREATE POLICY "Anyone can validate teacher registration keys" ON teacher_registration_keys
  FOR SELECT
  USING (expires_at >= now());

DROP POLICY IF EXISTS "Admins manage teacher registration keys" ON teacher_registration_keys;
CREATE POLICY "Admins manage teacher registration keys" ON teacher_registration_keys
  FOR ALL
  USING (auth_role() = 'admin')
  WITH CHECK (auth_role() = 'admin');

-- Class-subject junction used as an onboarding fallback.
CREATE TABLE IF NOT EXISTS class_subjects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(class_id, subject_id)
);

CREATE INDEX IF NOT EXISTS idx_class_subjects_class
  ON class_subjects(class_id);

ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users view class subjects" ON class_subjects;
CREATE POLICY "Authenticated users view class subjects" ON class_subjects
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admins manage class subjects" ON class_subjects;
CREATE POLICY "Admins manage class subjects" ON class_subjects
  FOR ALL
  USING (auth_role() = 'admin')
  WITH CHECK (auth_role() = 'admin');

-- Holidays used by attendance and tuition-event week calculations.
CREATE TABLE IF NOT EXISTS holidays (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  date DATE NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'custom' CHECK (type IN ('public', 'custom')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_holidays_date ON holidays(date);

ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users view holidays" ON holidays;
CREATE POLICY "Authenticated users view holidays" ON holidays
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admins manage custom holidays" ON holidays;
CREATE POLICY "Admins manage custom holidays" ON holidays
  FOR ALL
  USING (auth_role() = 'admin')
  WITH CHECK (auth_role() = 'admin');

-- Lightweight notification/intel feed used by library rewards.
CREATE TABLE IF NOT EXISTS intel (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info',
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_intel_profile_read
  ON intel(profile_id, read);

ALTER TABLE intel ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own intel" ON intel;
CREATE POLICY "Users manage own intel" ON intel
  FOR ALL
  USING (profile_id = auth.uid() OR auth_role() = 'admin')
  WITH CHECK (profile_id = auth.uid() OR auth_role() = 'admin');

-- Live classroom base tables. Later migrations add room fields,
-- realtime messages, whiteboard state, reflections, and RLS fixes.
CREATE TABLE IF NOT EXISTS live_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id UUID NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,
  class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  tuition_center_id UUID REFERENCES tuition_centers(id) ON DELETE SET NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'live', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_live_sessions_teacher
  ON live_sessions(teacher_id);
CREATE INDEX IF NOT EXISTS idx_live_sessions_class_center
  ON live_sessions(class_id, tuition_center_id);
CREATE INDEX IF NOT EXISTS idx_live_sessions_scheduled_at
  ON live_sessions(scheduled_at);

ALTER TABLE live_sessions ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_live_sessions_updated ON live_sessions;
CREATE TRIGGER trg_live_sessions_updated
  BEFORE UPDATE ON live_sessions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE IF NOT EXISTS live_session_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES live_sessions(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  is_completed BOOLEAN NOT NULL DEFAULT false,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_live_session_outcomes_session
  ON live_session_outcomes(session_id);

ALTER TABLE live_session_outcomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Teachers can manage their own live sessions" ON live_sessions;
CREATE POLICY "Teachers can manage their own live sessions" ON live_sessions
  FOR ALL
  USING (teacher_id = get_my_teacher_id() OR auth_role() = 'admin')
  WITH CHECK (teacher_id = get_my_teacher_id() OR auth_role() = 'admin');

DROP POLICY IF EXISTS "Students can view live sessions for their class" ON live_sessions;
CREATE POLICY "Students can view live sessions for their class" ON live_sessions
  FOR SELECT
  USING (class_id = get_my_student_class_id() OR auth_role() IN ('admin', 'teacher'));

DROP POLICY IF EXISTS "Teachers can manage outcomes for their sessions" ON live_session_outcomes;
CREATE POLICY "Teachers can manage outcomes for their sessions" ON live_session_outcomes
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM live_sessions
      WHERE live_sessions.id = live_session_outcomes.session_id
        AND (live_sessions.teacher_id = get_my_teacher_id() OR auth_role() = 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM live_sessions
      WHERE live_sessions.id = live_session_outcomes.session_id
        AND (live_sessions.teacher_id = get_my_teacher_id() OR auth_role() = 'admin')
    )
  );

DROP POLICY IF EXISTS "Students can view outcomes for their sessions" ON live_session_outcomes;
CREATE POLICY "Students can view outcomes for their sessions" ON live_session_outcomes
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM live_sessions
      WHERE live_sessions.id = live_session_outcomes.session_id
        AND live_sessions.class_id = get_my_student_class_id()
    )
  );

-- Storage bucket used by the teacher AI assistant.
INSERT INTO storage.buckets (id, name, public)
VALUES ('teacher-resources', 'teacher-resources', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Teacher resources are publicly accessible" ON storage.objects;
CREATE POLICY "Teacher resources are publicly accessible"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'teacher-resources');

DROP POLICY IF EXISTS "Authenticated users upload teacher resources" ON storage.objects;
CREATE POLICY "Authenticated users upload teacher resources"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'teacher-resources' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users delete teacher resources" ON storage.objects;
CREATE POLICY "Authenticated users delete teacher resources"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'teacher-resources' AND auth.role() = 'authenticated');

-- Global leaderboard used by student dashboard.
DROP FUNCTION IF EXISTS get_global_leaderboard(integer);
CREATE FUNCTION get_global_leaderboard(p_limit integer DEFAULT 20)
RETURNS TABLE(id uuid, full_name text, xp int, avatar_url text, class_name text)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT
    s.id,
    s.full_name,
    COALESCE(s.xp, 0) AS xp,
    p.avatar_url,
    c.name AS class_name
  FROM students s
  LEFT JOIN profiles p ON p.id = s.user_id
  LEFT JOIN classes c ON c.id = s.class_id
  ORDER BY COALESCE(s.xp, 0) DESC, s.full_name ASC
  LIMIT p_limit;
$$;

GRANT EXECUTE ON FUNCTION get_global_leaderboard(integer) TO authenticated;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE live_sessions;
EXCEPTION
  WHEN duplicate_object OR undefined_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE live_session_outcomes;
EXCEPTION
  WHEN duplicate_object OR undefined_object THEN NULL;
END $$;

NOTIFY pgrst, 'reload schema';
